### ISSUE TITLE
Contact Us form.

### ISSUE THREAD

**Issue by ghost** [ashchristopher/django-toronto#25]
We dont have one but we refer users to 'contact us'. We should have a form to collect info, and should link the 'Contact us' text throughout the app to link to said Contact Us form.

**Comment by mwarkentin** [comment]
If you have an email address you'd like to use (I'm assuming the form would send an email somewhere), you could start by adding mailto: links to the 'contact us' text.

**Comment by ashchristopher** [comment]
I am going to create a simple contact us form that just saves to the DB - once we are on VMFarms then ill look at sending out the emails.

**Comment by ashchristopher** [comment]
Simple form with validation created. I still need to style the errors, and provide feedback via the messages framework in django to the user. 

I might also move the BannedIp out of this app into a stand-alone app since we could probably use banishment other places =).

See: https://github.com/ashchristopher/django-toronto/tree/contact_us
